apiVersion: v1
kind: Service
metadata:
  name: mycryptobot
  namespace: blue-green
spec:
  type: NodePort
  selector:
    app: mycryptobot
    color: green
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
